apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2021-03-15T01:03:30Z"
    generation: 1
    labels:
      app: quotesapi
      app.kubernetes.io/component: quotesapi
      app.kubernetes.io/instance: quotesapi
    managedFields:
    - apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
      manager: oc
      operation: Update
      time: "2021-03-15T01:03:30Z"
    name: quotesapi
    namespace: kiniraj-quotes-dev
    resourceVersion: "19949476"
    selfLink: /apis/image.openshift.io/v1/namespaces/kiniraj-quotes-dev/imagestreams/quotesapi
    uid: 2ccd1907-278c-46c6-aeaa-1a5bd69cc989
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/kiniraj-quotes-dev/quotesapi
    publicDockerImageRepository: default-route-openshift-image-registry.apps.na45.prod.nextcle.com/kiniraj-quotes-dev/quotesapi
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2021-03-15T01:03:21Z"
    creationTimestamp: "2021-03-15T01:03:21Z"
    generation: 2
    name: quotesdb
    namespace: kiniraj-quotes-dev
    resourceVersion: "19949368"
    selfLink: /apis/image.openshift.io/v1/namespaces/kiniraj-quotes-dev/imagestreams/quotesdb
    uid: 0e4cf17e-9851-4332-bf37-97c90bdace75
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:5.7
      generation: 2
      importPolicy: {}
      name: "5.7"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/kiniraj-quotes-dev/quotesdb
    publicDockerImageRepository: default-route-openshift-image-registry.apps.na45.prod.nextcle.com/kiniraj-quotes-dev/quotesdb
    tags:
    - items:
      - created: "2021-03-15T01:03:21Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
        generation: 2
        image: sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
      tag: "5.7"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
