apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2021-06-08T17:57:13Z"
    generation: 1
    labels:
      app: quotesapi
      app.kubernetes.io/component: quotesapi
      app.kubernetes.io/instance: quotesapi
    managedFields:
    - apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
      manager: oc
      operation: Update
      time: "2021-06-08T17:57:13Z"
    name: quotesapi
    namespace: kiniraj-quotes-dev
    resourceVersion: "83791876"
    selfLink: /apis/image.openshift.io/v1/namespaces/kiniraj-quotes-dev/imagestreams/quotesapi
    uid: 40250cb1-f1ff-449f-9cb4-689928ff92e1
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/kiniraj-quotes-dev/quotesapi
    publicDockerImageRepository: default-route-openshift-image-registry.apps.na45.prod.nextcle.com/kiniraj-quotes-dev/quotesapi
    tags:
    - items:
      - created: "2021-06-08T17:57:47Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/kiniraj-quotes-dev/quotesapi@sha256:228acc32295e8ba9281e1b60bc13b6ea41626be1cba3346d46b5655fa842a815
        generation: 1
        image: sha256:228acc32295e8ba9281e1b60bc13b6ea41626be1cba3346d46b5655fa842a815
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2021-06-08T17:57:04Z"
    creationTimestamp: "2021-06-08T17:57:03Z"
    generation: 2
    name: quotesdb
    namespace: kiniraj-quotes-dev
    resourceVersion: "83791307"
    selfLink: /apis/image.openshift.io/v1/namespaces/kiniraj-quotes-dev/imagestreams/quotesdb
    uid: 2326a5dd-ba1f-40c5-8754-b11f9423cc06
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:5.7
      generation: 2
      importPolicy: {}
      name: "5.7"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/kiniraj-quotes-dev/quotesdb
    publicDockerImageRepository: default-route-openshift-image-registry.apps.na45.prod.nextcle.com/kiniraj-quotes-dev/quotesdb
    tags:
    - items:
      - created: "2021-06-08T17:57:04Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
        generation: 2
        image: sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
      tag: "5.7"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
